# Path to your oh-my-zsh installation.
export DOTFILES_ZSH_PATH=$HOME/dotfiles/zsh
export ZSH=$DOTFILES_ZSH_PATH/oh-my-zsh

# Use another custom folder than $ZSH/custom
export ZSH_CUSTOM=$DOTFILES_ZSH_PATH/custom

# Set name of the theme to load.
# Optionally, if you set this to "random", it'll load a random theme each
ZSH_THEME="alanpeabody"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git airbnb-zsh)

# User configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"


# You may need to manually set your language environment
export LANG=en_US.UTF-8
export DISABLE_AUTO_UPDATE="true"

source $ZSH/oh-my-zsh.sh
# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Prompts
RPROMPT=$RPROMPT'$(battery)'
PROMPT='%{$fg[blue]$bg[grey]%}$(date) %{$reset_color%}
'$PROMPT

