export ZDOTFILESDIR=$HOME/dotfiles/zsh
. $ZDOTFILESDIR/zsh-selected
. $ZDOTFILESDIR/zshrc-$ZSH_SELECTED

if [[ -e "$ZDOTFILESDIR/local.zsh" ]]; then
  . $ZDOTFILESDIR/local.zsh
fi

export PATH=$PATH:$ZDOTFILESDIR/bin
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/code/naoshima/codec
export PATH=$PATH:$HOME/dotfiles/bin/macos

# # for pyenv
# #export PATH="/Users/vctor_peng/.pyenv:$PATH"  # for macOS
# export PATH="/Users/ziliangpeng/.pyenv:$PATH"  # for macOS
# export PATH="/home/zpeng/.pyenv/bin:$PATH"  # for ubuntu
# #eval "$(pyenv init -)"
# # for enabling pyenv on every new shell
# if command -v pyenv 1>/dev/null 2>&1; then
#   eval "$(pyenv init -)"
# fi

# let Prezto point to the default history file (as oh-my-zsh)
HISTFILE=$HOME/.zsh_history

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/ziliangpeng/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/ziliangpeng/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/ziliangpeng/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/ziliangpeng/google-cloud-sdk/completion.zsh.inc'; fi

export NAOSHIMA=~/code/naoshima

# Modular
export MODULAR_HOME="$HOME/.modular"
export PATH="$MODULAR_HOME/pkg/packages.modular.com_mojo/bin:$PATH"
