brew "pyenv"
brew "tmux"
brew "wget"
brew "ffmpeg"
brew "imagemagick"
cask "google-chrome"
cask "iterm2"
cask "iina"
cask "caffeine"
cask "spectacle"
cask "manico"
cask "dropbox"
cask "visual-studio-code"
cask "notion"
cask "squirrel"
cask "wechat"

# What NOT to install
# cask "google-drive" # this doesn't work.